name: Pranction
version: 0.3
author: Program
main: fr.program.pranction.Pranction
api-version: 1.18
commands:
  info:
    aliases:
      - information
    description: Informations sur le plugin Pranction.
    permission: pranction.player.info.use
  modt:
    aliases:
      - modtool
    description: Outils utiles a la moderation.
    permission: pranction.moderator.modt.use
  mute:
    description: Rendre muet un joueur
    permission: pranction.moderator.mute.use
  tempmute:
    description: Rendre muet un joueur temporairement
    permission: pranction.moderator.tempmute.use
  unmute:
    description: Redonner la parole à un joueur
    permission: pranction.moderator.unmute.use
  sp:
    aliases:
      - sanctionplayer
    description: Donner des sanctions à un joueur
    permission: pranction.moderator.sp.use
  pban:
    aliases:
      - permaban
    description: Bannir à vie un joueur
    permission: pranction.moderator.pban.use
  tempban:
    description: Bannir temporairement un joueur
    permission: pranction.moderator.tempban.use
  unban:
    description: Ne plus bannir un joueur
    permission: pranction.moderator.unban.use
  cleardata:
    description: Supprime les donnees sauvegarde du joueur
    permission: pranction.admin.cleardata.use
  whois:
    description: Informations sur le joueur
    permission: pranction.moderator.whois.use
  vanish:
    description: Permet de se rendre invisible
    permission: pranction.moderator.vanish.use